name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: '0.1.0'
      release_title:
        description: 'Release Title'
        required: true
        default: 'Initial Release'
      draft:
        description: 'Create as draft'
        required: false
        default: 'true'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: 'true'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_SECRET }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: ${{ github.event.inputs.release_title }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
      - uses: actions/checkout@v4
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ github.event.inputs.release_title }}
          artifacts: "release.zip"
          token: ${{ secrets.BUILD_SECRET }}

