name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: '0.1.0'
      release_title:
        description: 'Release Title'
        required: true
        default: 'Initial Release'
      draft:
        description: 'Create as draft'
        required: false
        default: 'false'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: 'false'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: ${{ github.event.inputs.release_title }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}